apiVersion: v1
kind: Service
metadata:
  name: webhooks-extension
  namespace: tekton-pipelines
  labels:
    app: webhooks-extension
    tekton-dashboard-extension: "true"
  annotations:
    tekton-dashboard-display-name: Webhooks
    tekton-dashboard-endpoints: "webhooks.web"
<<<<<<< HEAD
    tekton-dashboard-bundle-location: "web/extension.232c3e74.js"
=======
    tekton-dashboard-bundle-location: "web/extension.4cc4b166.js"
>>>>>>> 9346f6a7574537bf9a4a2a4baeba989f4a9dfcd6
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: webhooks-extension
