apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: ingress-task
  namespace: tekton-pipelines
spec:
  inputs:
    params:
    - name: Mode
      description: Whether to create or delete an Ingress
      default: "create"
      type: string
    - name: CallbackURL 
      description: The external access URL
      default: "listener.replaceme.nip.io"
      type: string
    - name: EventListenerServiceName 
      description: The EventListener Service name
      default: "listener"
      type: string
    - name: EventListenerPort
      description: The EventListener port
      default: "8080"
      type: string
  steps:
  - name: create-or-delete-ingress
    image: lachlanevenson/k8s-kubectl:latest
    command:
    - sh
    args:
    - -ce
    - |
      set -e
      if [ $(inputs.params.Mode) = "create" ] ; then
        echo "Creating the Ingress"
        cat <<EOF | kubectl apply -f -
        apiVersion: extensions/v1beta1
        kind: Ingress
        metadata:
          name: $(inputs.params.EventListenerServiceName)
        spec:
          rules:
          - host: $(inputs.params.CallbackURL)
            http:
              paths:
              - backend:
                  serviceName: $(inputs.params.EventListenerServiceName)
                  servicePort: $(inputs.params.EventListenerPort)
      EOF
      fi
           
      if [ $(inputs.params.Mode) = "delete" ] ; then
        echo "Deleting Ingress"
        kubectl delete ingress $(inputs.params.EventListenerServiceName)
      fi